### ISSUE TITLE
use vectorTranslateAsync with sql

### ISSUE THREAD

**Issue by LuckDogHu** [mmomtchev/node-gdal-async#101]
gdal.openAsync(join(public_path, 'aaa.geojson')).then((in_ds) => {
      const sql = `SELECT *,'LABEL(f:Arial,t:'||floor||')' AS OGR_STYLE FROM aaa`;
      gdal
        .vectorTranslateAsync(join(public_path, `aaa.dxf`), in_ds, [
          '-f',
          'DXF',
          '-sql',
          sql,
        ])
        .then((out2_ds) => {
          in_ds.close();
          out2_ds.close();
        });
    });
--------------------------------------------------------
Error: SQL Expression Parsing Error: syntax error, unexpected $undefined, expecting FROM. Occurred around :
SELECT *,'LABEL(f:Arial,t:'||floor||')' AS OGR_STYLE FROM aaa
---------------------------------------------------------------------
so how can i get in_ds tabel_name for exec this sql
can give me any help thank you

**Comment by mmomtchev** [comment]
I do not think your problem is related to `gdal-async`:

```shell
$ ogr2ogr -sql "SELECT *,'LABEL(f:Arial,t:'||floor||')' AS OGR_STYLE FROM aaa" out.json test/data/park.geo.json
ERROR 1: SQL Expression Parsing Error: syntax error, unexpected $undefined, expecting FROM. Occurred around :
SELECT *,'LABEL(f:Arial,t:'||floor||')' AS OGR_STYLE FROM aaa
                           ^
```

Check the validity of your SQL statement.
