### ISSUE TITLE
How to use ogr2ogr

### ISSUE THREAD

**Issue by abouroubi** [mmomtchev/node-gdal-async#155]
I saw in the readme that 
"Library versions of GDAL's command-line utilities gdalinfo, gdal_translate, ogr2ogr and gdalwarp (since 3.4)"

Do you have an example on how we can do it with Typescript ?

Thanks

**Comment by mmomtchev** [comment]
As usual, you can find many examples in the unit tests.

**Comment by mmomtchev** [comment]
M. Bouroubi, can you please explain me, because I am totally amazed that someone can show that he is taking part in a criminal extortion, and then to continue the conversation like nothing happened, how exacly do you see this situation? Do you do this often? Does it work?

**Comment by abouroubi** [comment]
I have no idea what you are talking about, I just wanted to use the package, if you can't help me no worries.
Hope your situation get better.
