### ISSUE TITLE
Support for utilities as a library functions like VectorTranslate ?

### ISSUE THREAD

**Issue by ThomasG77** [mmomtchev/node-gdal-async#18]
Since some years, I've used in Python utilities that do the same as command line with native code because of RFC https://gdal.org/development/rfc/rfc59_utilities_as_a_library.html

It has evolved, so you can use a `VectorTranslate` to do the equivalent of ogr2ogr amonst others.

Methods can be `Info`, `Translate`, `Warp`, `VectorTranslate`, `DEMProcessing`, `BuildVRT`, `Rasterize`, `Nearblack` and `Grid` like in https://gdal.org/python/osgeo.gdal-module.html#section-Functions
Is there any plan to go in this direction or should I only keep using the command line tools from a Node.js `exec`?

**Comment by mmomtchev** [comment]
3.4 will have `gdal.info`, `gdal.translate`, `gdal.vectorTranslate`, `gdal.warp` and an in-house pure JS `gdal.calc` that supports JS functions
GDAL 3.4.0 is at rc3 since Friday, if this release is promoted tomorrow, then `gdal-async@3.4` will follow a few hours later

**Comment by mmomtchev** [comment]
3.4.0 is now available

**Comment by robinsummerhill** [comment]
Is there any plan to support GDALRasterize from the C/C++ API?

**Comment by mmomtchev** [comment]
Why not, I didn't consider it for 3.5 but it is a trivial addition
