### ISSUE TITLE
gdal.open() does not accept driver specific Open Options

### ISSUE THREAD

**Issue by robinsummerhill** [mmomtchev/node-gdal-async#24]
GDAL drivers can implement driver-specific options used when opening datasets. For example, the GeoJSON driver implements a [`DATE_AS_STRING` option](https://gdal.org/drivers/vector/geojson.html#open-options) to control how dates are interpreted when opening a GeoJSON file.

The C API allows you to specify these options when opening a dataset with [`GDALOpenEx()`](https://gdal.org/drivers/vector/geojson.html#open-options) but this is not possible using the NodeJS bindings.

`gdal.open()` should be extended to allow passing driver-specific Open Options.

**Comment by mmomtchev** [comment]
I am adding this for 3.5, but in the mean time you can use
`gdal.config.set('OGR_GEOJSON_DATE_AS_STRING', 'ON')`

**Comment by robinsummerhill** [comment]
Thank you! I thought it might be possie with gdal.config but couldn't work out the right key name.
