### ISSUE TITLE
webdoc documentation generator

### ISSUE THREAD

**Issue by ShukantPal** [mmomtchev/node-gdal-async#31]
Hey there, given the long form of your documentation - [webdoc](www.webdoclabs.com) may be better suited to your project :) I can help you move over. Example of webdoc: https://webdoc-labs.github.io/example-documentation/index.html, (customized) https://api.pixijs.io

**Comment by mmomtchev** [comment]
Doesn't seem to support C++?
`node-gdal-async` uses a special plugin for `documentation.js` that has been developed for this project

**Comment by ShukantPal** [comment]
@mmomtchev It seems like documentation.js isn't parsing the C++ code and is just working off of the documentation comments. I can add that kind of support easily.

**Comment by mmomtchev** [comment]
I just finished a huge migration towards `documentation.js` which included writing a special plugin, I am really not inclined to invest anything into a new documentation system
