### ISSUE TITLE
Amazon Linux Lambdas advice

### ISSUE THREAD

**Issue by alexcroox** [mmomtchev/node-gdal-async#45]
The readme mentions "pruning" the module to reduce the size, are there any guidelines on this? I'm unsure what I can and can't remove.

**Comment by alexcroox** [comment]
I've nearly got this working on AWS lambda, stumbling on the @mapbox/node-pre-gyp dep this library has:

![Screenshot 2022-10-12 at 14 41 03](https://user-images.githubusercontent.com/1065835/195359641-7bba1cdb-c6d0-463c-8da0-fb22425cc792.png)

Which comes from here:

![Screenshot 2022-10-12 at 14 41 40](https://user-images.githubusercontent.com/1065835/195359703-b5717ca4-8dec-4ea0-aeba-78b5d2d5e145.png)

![image](https://user-images.githubusercontent.com/1065835/195360086-888d2c3f-8524-4800-b9f3-0c5a33d3680a.png)

I'll update if I can figure it out

**Comment by mmomtchev** [comment]
> The readme mentions "pruning" the module to reduce the size, are there any guidelines on this? I'm unsure what I can and can't remove.

The readme says that there is a npm script that can be launched with `npm run prune` that does the pruning

**Comment by mmomtchev** [comment]
> I've nearly got this working on AWS lambda, stumbling on the @mapbox/node-pre-gyp dep this library has:

Although you can submit this to `@mapbox/node-pre-gyp`, normally, a npm-packaged project is supposed to have a `package.json` file
