### ISSUE TITLE
npm version is old

### ISSUE THREAD

**Issue by stefanocudini** [mmomtchev/node-gdal-async#52]
thank you for your fantastic library

I noticed that the npm version I use is very old compared to the latest one on github

https://www.npmjs.com/package/gdal-async?activeTab=versions

maybe I can keep my code up to date with some other method or use npmjs.org as default distribution channel?

cheers!
Stef

**Comment by mmomtchev** [comment]
There is no published version after 3.5.3, 3.6.0 is coming very shortly. 3.6.0 drops a number of old Node versions and OS and it adds new ones, so all Github actions need to be adjust accordingly.

**Comment by stefanocudini** [comment]
I'm just that glibc 2.28 requirement breaks compatibility with Ubuntu 18.04.. but after `npm install node-async` this is not reported.. at runtime compare this:
```Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found```

**Comment by stefanocudini** [comment]
mmh the same if I'm shift to v16.x
`Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/z4k/geopicker/node_modules/gdal-async/lib/binding/node-v93-linux-x64/gdal.node`

**Comment by mmomtchev** [comment]
Yes, Ubuntu 18.04 is no longer supported. Node.js 18 dropped old glibc compatibility and it became increasingly difficult to support two different build chains - one for Node.js 14/16 - and one for Node.js 18. Ubuntu 20.04 is the new requirement. Ubuntu 18.04 is almost 5 years old and it is not supported anymore.

**Comment by stefanocudini** [comment]
mmh right, this seems reasonable to me... for docker containers it is not difficult to maintain this compatibility... but unfortunately my development environment is in ubuntu 18 so for the moment I have to keep the 3.5.1 version I hope I don't miss too many updates ..

Many thanks for your time and happy new year!
