### ISSUE TITLE
Get elevation/altitude from GeoTIFF

### ISSUE THREAD

**Issue by jfoclpf** [mmomtchev/node-gdal-async#74]
First of all I'd like to congratulate you for the public service.

I also developed [an open and free Geo API for Portugal](https://github.com/jfoclpf/geoapi.pt) and now I'd like to provide altitude without the need of external APIs, that is, using the GeoTIFF file provided by the government agency. 

How can I get that using your library? I open the TIF file with `gdal.open` and then?

**Comment by mmomtchev** [comment]
There is an example in the package that does exactly this

**Comment by jfoclpf** [comment]
thank you @mmomtchev , just to confirm, do you mean this?
https://github.com/mmomtchev/node-gdal-async/blob/master/examples/serve.js
